### ISSUE TITLE
EFI error codes in efi/types.h should have high bit set

### ISSUE THREAD

**Issue by tkchia** [krinkinmu/efi#2]
Hello @krinkinmu,

I encountered an issue while running the code in QEMU under some configurations:  `loader->system->boot->get_memory_map( )` was returning a "buffer too small" error code, but the `exit_efi_boot_services( )` routine did not recognize it.

I found that this was because the error code definitions in `efi/types.h` were not quite correct.  Specifically,
```
static const efi_status_t EFI_LOAD_ERROR = 1;
static const efi_status_t EFI_INVALID_PARAMETER = 2;
static const efi_status_t EFI_UNSUPPORTED = 3;
static const efi_status_t EFI_BUFFER_TOO_SMALL = 5;
```
should really be
```
static const efi_status_t EFI_LOAD_ERROR = 0x8000000000000001;
static const efi_status_t EFI_INVALID_PARAMETER = 0x8000000000000002;
static const efi_status_t EFI_UNSUPPORTED = 0x8000000000000003;
static const efi_status_t EFI_BUFFER_TOO_SMALL = 0x8000000000000005;
```
(UEFI sets the top bit of return statuses for error codes, and clears the top bit for warning codes (and success).)

Thank you!

**Comment by krinkinmu** [comment]
Good catch, corrected the error codes in https://github.com/krinkinmu/efi/commit/72f85a8b5e1db3a0a53954f9fa75f5426d5e68ad.

**Comment by tkchia** [comment]
Hello @krinkinmu 

Thank you very much for the fix!
